import os
from PIL import Image

def apply_palette_map(ascii_art, palette_map):
    lines = [l for l in ascii_art.strip().splitlines()]
    img = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    for y in range(16):
        line = lines[y] if y < len(lines) else ""
        for x in range(16):
            char = line[x] if x < len(line) else "."
            if char in palette_map and palette_map[char] is not None:
                color = palette_map[char]
                if len(color) == 3:
                    color = color + (255,)
                img.putpixel((x, y), color)
    return img

GRAY_PALETTE = {
    '#': (45, 45, 45),    # Contour / dark
    'd': (110, 110, 110), # Dark midtone
    'm': (170, 170, 170), # Base metal
    'h': (220, 220, 220), # Highlight
    'H': (255, 255, 255), # Specular glint
    '.': None
}

PICKAXE_HEAD_ART = """
......##hHHHh#..
...###hHHhhd#...
..#hHhhhmd##....
.#hHhmd##.......
#hHmd#..........
#hm##...........
##..............
................
................
..............##
...........#dmh#
..........#dmHh#
.......##dmhHh#.
....##dmhhHh#...
...#dhhHHh###...
..#hHHHh##......
"""

AXE_HEAD_ART = """
.....###hHHHHh#.
...##hHHhhhhhmd#
..#hHHhmmmmmmdd#
.#hHhmmmd####d##
#hHhmmm#........
#hHmmmd#........
#hHmmmd#........
.#hHhmm#........
..#hHhmm#.......
...#hHhm#.......
....#hHh#.......
.....#hH#.......
......#h#.......
.......##.......
................
................
"""

SHOVEL_HEAD_ART = """
.......#####....
.....##hHHHh##..
...##hHHhhhhmd#.
..#hHHhmmmmmmdd#
.#hHhmmmd####d##
.#hHmmmd#.......
.#hHmmmd#.......
.#hHmmmd#.......
.#hHhmm#........
..#hHhm#........
...#hHh#........
....#hH#........
.....#h#........
......##........
................
................
"""

SWORD_BLADE_ART = """
..............hH
.............hHm
............hHm#
...........hHm#d
..........hHm#d.
.........hHm#d..
........hHm#d...
.......hHm#d....
......hHm#d.....
.....hHm#d......
....hHm#d.......
...hHm#d........
..hHm#d.........
.hHm#d..........
#m#d............
.#d.............
"""

HOE_HEAD_ART = """
......##hHHHHh#.
....##hHHhhhhhmd
...#hHHhmmmmmmdd
..#hHhmmmd####d#
.#hHhmmmd#......
#hHhmmmd#.......
#hHmmmd#........
.#hHhm#.........
..#hHh#.........
...#hH#.........
....#h#.........
.....##.........
................
................
................
................
"""

HANDLE_ART = """
..............#H
.............#Hm
............#Hm#
...........#Hm#d
..........#Hm#d.
.........#Hm#d..
........#Hm#d...
.......#Hm#d....
......#Hm#d.....
.....#Hm#d......
....#Hm#d.......
...#Hm#d........
..#Hm#d.........
.#Hm#d..........
#m#d............
.#d.............
"""

BINDING_ART = """
................
................
................
................
......####......
.....#hHHh#.....
....#hHhhHh#....
...#hH#dd#Hh#...
...#hH#dd#Hh#...
....#hHhhHh#....
.....#hHHh#.....
......####......
................
................
................
................
"""

TIP_ART = """
..............#H
.............#Hh
............#Hhm
...........#Hhm#
..........#Hhm#d
.........#Hhm#d.
........#Hhm#d..
.......#Hhm#d...
......#Hhm#d....
.....#Hhm#d.....
....#Hhm#d......
...#Hhm#d.......
..#Hhm#d........
.#Hhm#d.........
#m#d............
.#d.............
"""

GRIP_ART = """
................
................
................
................
......#####.....
.....#hHHHh#....
....#hHhhhhh#...
...#hH#ddddd#...
...#hH#ddddd#...
....#hHhhhhh#...
.....#hHHHh#....
......#####.....
................
................
................
................
"""

PARTS = {
    'pickaxe_head': PICKAXE_HEAD_ART,
    'axe_head': AXE_HEAD_ART,
    'shovel_head': SHOVEL_HEAD_ART,
    'sword_blade': SWORD_BLADE_ART,
    'hoe_head': HOE_HEAD_ART,
    'handle': HANDLE_ART,
    'binding': BINDING_ART,
    'tip': TIP_ART,
    'grip': GRIP_ART,
}

out_dir = "src/main/resources/assets/modernmachines/textures/item/template/part"
os.makedirs(out_dir, exist_ok=True)

for name, art in PARTS.items():
    img = apply_palette_map(art, GRAY_PALETTE)
    img.save(f"{out_dir}/{name}.png")

print("All tool part grayscale templates generated successfully!")
