import os
from PIL import Image

def apply_palette_map(ascii_art, palette_map):
    lines = [l for l in ascii_art.strip().splitlines()]
    img = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    for y in range(16):
        line = lines[y] if y < len(lines) else ""
        for x in range(16):
            char = line[x] if x < len(line) else "."
            if char in palette_map and palette_map[char] is not None:
                color = palette_map[char]
                if len(color) == 3:
                    color = color + (255,)
                img.putpixel((x, y), color)
    return img

TOOL_PALETTE = {
    '#': (45, 45, 45),     # Dark steel outline
    'd': (110, 110, 110),  # Steel shadow
    'm': (170, 170, 170),  # Steel base
    'h': (220, 220, 220),  # Steel highlight
    'H': (255, 255, 255),  # Specular glint
    'W': (155, 115, 75),   # Wood handle
    'w': (110, 80, 50),    # Wood shadow
    '.': None
}

MODULAR_PICKAXE_ART = """
......##hHHHh#..
...###hHHhhd#...
..#hHhhhmd##....
.#hHhmd#W#......
#hHmd#.W#w#.....
#hm##.W#..w#....
##...W#....w#...
....W#......w#..
...W#........w#.
..W#..........w#
.W#............#
W#..............
w#..............
.w#.............
..w#............
...w#...........
"""

MODULAR_AXE_ART = """
.....###hHHHHh#.
...##hHHhhhhhmd#
..#hHHhmmmmmmdd#
.#hHhmmmd####d##
#hHhmmm#W#......
#hHmmmd#W#w#....
#hHmmmd#W#..w#..
.#hHhmm#W#...w#.
..#hHhm#W#....w#
...#hHh#W#.....w
....#hH#W#......
.....#h#W#......
......##W#......
.......#W#......
........w#......
.........w#.....
"""

MODULAR_SHOVEL_ART = """
.......#####....
.....##hHHHh##..
...##hHHhhhhmd#.
..#hHHhmmmmmmdd#
.#hHhmmmd####d##
.#hHmmmd#W#.....
.#hHmmmd#.W#....
.#hHmmmd#..W#...
.#hHhmm#....W#..
..#hHhm#.....W#.
...#hH#.......W#
....#h#........W
.....#..........
................
................
................
"""

MODULAR_SWORD_ART = """
..............hH
.............hHm
............hHm#
...........hHm#d
..........hHm#d.
.........hHm#d..
........hHm#d...
.......hHm#d....
......hHm#d.....
..##.hHm#d..##..
.###hHm#d..###..
..#d#m#d..#d#...
...#W#d..#W#....
...#W#..#W#.....
....w#..w#......
.....w##w#......
"""

MODULAR_HOE_ART = """
......##hHHHHh#.
....##hHHhhhhhmd
...#hHHhmmmmmmdd
..#hHhmmmd####d#
.#hHhmmmd#W#....
#hHhmmmd#..W#...
#hHmmmd#....W#..
.#hHhm#......W#.
..#hHh#.......W#
...#hH#........W
....#h#.........
.....##.........
................
................
................
................
"""

TOOLS = {
    'modular_pickaxe': MODULAR_PICKAXE_ART,
    'modular_axe': MODULAR_AXE_ART,
    'modular_shovel': MODULAR_SHOVEL_ART,
    'modular_sword': MODULAR_SWORD_ART,
    'modular_hoe': MODULAR_HOE_ART,
}

out_dir = "src/main/resources/assets/modernmachines/textures/item"
for name, art in TOOLS.items():
    img = apply_palette_map(art, TOOL_PALETTE)
    img.save(f"{out_dir}/{name}.png")

print("Modular tool textures generated successfully!")
